version: '3.8'

services:
  react-app:
    build: 
      context: ./client
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    networks:
      - mon-reseau

  backend-app:
    build:
      context: ./back-end
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    networks:
      - mon-reseau

networks:
  mon-reseau:

volumes:
  db-data:
