"""empty message

Revision ID: 2821f266196a
Revises: c06c07c22afa
Create Date: 2024-03-25 15:11:57.298105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2821f266196a'
down_revision = 'c06c07c22afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evenement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startdate', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('enddate', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('nbparticipantmax', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evenement', schema=None) as batch_op:
        batch_op.drop_column('nbparticipantmax')
        batch_op.drop_column('enddate')
        batch_op.drop_column('startdate')

    # ### end Alembic commands ###
