"""empty message

Revision ID: 68aba03d6e6c
Revises: 3d72aeb739a8
Create Date: 2024-02-18 18:54:25.409380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68aba03d6e6c'
down_revision = '3d72aeb739a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=32), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
