"""empty message

Revision ID: 6bcf30a59e20
Revises: 
Create Date: 2023-12-04 17:46:01.457357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bcf30a59e20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'comments', ['id'])
    op.drop_column('comments', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('likes', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'comments', type_='unique')
    # ### end Alembic commands ###
